HTML = """
<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>FleetAI 2.0</title>
<style>
body{font-family:Arial;background:#f3f5f7;margin:0;color:#111827}.wrap{max-width:1280px;margin:auto;padding:24px}
.card{background:white;border-radius:16px;padding:18px;margin:14px 0;box-shadow:0 2px 12px #0001}.grid{display:grid;grid-template-columns:repeat(7,1fr);gap:12px}
.stat{background:#111827;color:white;border-radius:14px;padding:16px}.stat b{font-size:22px;display:block;margin-top:8px}
input,select{padding:12px;font-size:16px;border:1px solid #ddd;border-radius:10px;margin:4px}input.msg{width:78%;font-size:18px}button{padding:10px 14px;font-size:15px;border:0;border-radius:10px;background:#2563eb;color:white;cursor:pointer}
table{width:100%;border-collapse:collapse}td,th{padding:9px;border-bottom:1px solid #eee;text-align:left}.tabs button{background:#e5e7eb;color:#111}.tabs button.active{background:#2563eb;color:white}
.badge{padding:4px 8px;border-radius:999px;background:#e0f2fe;color:#0369a1;font-size:12px}.warn{background:#fff7ed;border-left:5px solid #f97316}
.ok{color:#16a34a}.bad{color:#dc2626}.calendar{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:12px}
.daycard{border:1px solid #e5e7eb;border-radius:14px;padding:12px;background:#f9fafb}.daycard h4{margin:0 0 10px 0}
.event{background:white;border-left:4px solid #2563eb;border-radius:10px;padding:9px;margin:8px 0;box-shadow:0 1px 6px #0001}
.event.income{border-left-color:#16a34a}.event.repair,.event.service,.event.expense{border-left-color:#dc2626}.event.downtime{border-left-color:#f97316}
.event .sum{font-weight:bold}.event .raw{font-size:13px;color:#6b7280;margin-top:4px}
@media(max-width:800px){.grid{grid-template-columns:1fr 1fr}input.msg{width:100%;margin-bottom:8px}table{font-size:12px}}
</style></head><body><div class="wrap"><h1>🚗 FleetAI 2.0</h1>
<div id="summary"></div>
<div class="card"><input class="msg" id="msg" placeholder="703 получил 13000 / 703 простой с 11 июля / 703 замена масла 2500 работа 700"><button onclick="add()">Записать</button><p id="res"></p></div>

<div class="card warn"><h2>Инвесторы</h2><div id="investors"></div></div>

<div class="card">
<h2>Добавить машину</h2>
<select id="owner_type"><option value="own">Моя машина</option><option value="investor">Машина инвестора</option></select>
<input id="code" placeholder="Код 777"><input id="brand" placeholder="Марка"><input id="model" placeholder="Модель"><input id="plate" placeholder="Госномер">
<input id="year" placeholder="Год"><input id="purchase_date" placeholder="Дата покупки"><input id="purchase_price" placeholder="Цена покупки"><input id="mileage" placeholder="Пробег">
<input id="investor_name" placeholder="Имя инвестора"><input id="investor_percent" placeholder="% инвестора"><input id="settlement_day" placeholder="Расчетный день 15"><button onclick="addCar()">Добавить авто</button><p id="carRes"></p>
</div>

<div class="card">
<h2>Машины</h2><div class="tabs"><button id="tab_all" class="active" onclick="loadCars('all')">Все</button><button id="tab_own" onclick="loadCars('own')">Мои</button><button id="tab_investor" onclick="loadCars('investor')">Инвесторов</button></div>
<table id="cars"></table></div>

<div id="carCard"></div>

<div class="card"><h2>Последние операции</h2><table id="ops"></table></div>
</div><script>
let currentFilter='all';
async function api(u,o){let r=await fetch(u,o);return await r.json()}
function rub(n){return (n||0).toLocaleString('ru-RU')+' ₽'}
async function loadSummary(){let s=await api('/api/summary'); summary.innerHTML=`<div class="grid"><div class="stat">Всего <b>${s.cars}</b></div><div class="stat">Мои <b>${s.own_cars}</b></div><div class="stat">Инвесторов <b>${s.investor_cars}</b></div><div class="stat">Доход <b>${rub(s.income)}</b></div><div class="stat">Расход <b>${rub(s.expenses)}</b></div><div class="stat">Прибыль <b>${rub(s.profit)}</b></div><div class="stat">Простой <b>${s.downtime_days||0} дн.</b></div></div>`}
async function loadInvestors(){let d=await api('/api/investors'); if(!d.length){investors.innerHTML='Пока нет машин инвесторов';return} investors.innerHTML=d.map(i=>`<div class="card"><h3>${i.name}</h3><b>Вложил:</b> ${rub(i.total_invested)} | <b>Выплачено:</b> ${rub(i.total_payouts)} | <b>Остаток:</b> ${rub(i.balance)} | <b>Общая прибыль:</b> ${rub(i.total_profit)} | <b>Доля инвестора:</b> ${rub(i.total_to_investor)} | <b>Простой:</b> ${i.total_downtime_days||0} дн.<table><tr><th>Машина</th><th>%</th><th>Доход</th><th>Расход</th><th>Прибыль</th><th>Инвестору</th><th>Простой</th><th>Карточка</th></tr>${i.cars.map(c=>`<tr><td>${c.code} ${c.car}</td><td>${c.percent}%</td><td>${rub(c.income)}</td><td>${rub(c.expenses)}</td><td>${rub(c.profit)}</td><td>${rub(c.to_investor)}</td><td>${c.downtime_days||0} дн.</td><td><button onclick="openCar('${c.code}')">Открыть</button></td></tr>`).join('')}</table></div>`).join('')}
async function loadCars(filter='all'){currentFilter=filter; ['all','own','investor'].forEach(x=>document.getElementById('tab_'+x).classList.remove('active')); document.getElementById('tab_'+filter).classList.add('active'); let url='/api/cars'; if(filter!=='all')url+='?owner_type='+filter; let c=await api(url); cars.innerHTML='<tr><th>Тип</th><th>Код</th><th>Авто</th><th>Госномер</th><th>Инвестор</th><th>%</th><th>Пробег</th><th>Стоимость</th><th>Доход</th><th>Расход</th><th>Прибыль</th><th>Простой</th><th>Расчет</th><th>Карточка</th></tr>'+c.map(x=>`<tr><td><span class="badge">${x.owner_type==='investor'?'Инвестор':'Моя'}</span></td><td>${x.code}</td><td>${x.brand||''} ${x.model||''}</td><td>${x.plate||''}</td><td>${x.investor_name||''}</td><td>${x.investor_percent||0}</td><td>${x.mileage||0}</td><td>${rub(x.full_cost)}</td><td>${rub(x.income)}</td><td>${rub(x.expenses)}</td><td class="${x.profit>=0?'ok':'bad'}">${rub(x.profit)}</td><td>${x.downtime_days||0} дн.</td><td>${x.settlement_day||15} число<br><button onclick="openPeriod('${x.code}')">Расчет</button></td><td><button onclick="openCar('${x.code}')">Открыть</button></td></tr>`).join('')}
function groupByDate(operations){let groups={};operations.forEach(o=>{let day=(o.date||'').split(' ')[0]||'Без даты';if(!groups[day])groups[day]=[];groups[day].push(o)});return groups}
function eventTitle(o){if(o.type==='income')return'💰 Доход';if(o.type==='repair')return'🔧 Ремонт';if(o.type==='service')return'🛠 ТО';if(o.type==='expense')return'💸 Расход';if(o.type==='car_investment')return'📈 Доп. вложение';if(o.type==='downtime')return'🚫 Простой';if(o.type==='downtime_closed')return'✅ Простой закрыт';if(o.type==='settlement_period')return'📅 Расчетный период';return'📝 Запись'}
function renderCalendar(operations){let groups=groupByDate(operations);return `<div class="calendar">${Object.keys(groups).map(day=>`<div class="daycard"><h4>${day}</h4>${groups[day].map(o=>`<div class="event ${o.type}"><div><b>${eventTitle(o)}</b></div><div>${o.description||''}</div><div class="sum">${rub(o.amount)}</div>${o.mileage?`<div>Пробег: ${o.mileage}</div>`:''}<div class="raw">${o.raw||''}</div></div>`).join('')}</div>`).join('')}</div>`}
async function openPeriod(code){let d=await api('/api/period/'+code); if(!d.ok){alert(d.message);return} let p=d.current_period; let html=`<div class="card warn"><h2>Расчетный период машины ${code}</h2><p><b>Период:</b> ${p.start_date} — ${p.end_date}</p><p><b>Расчетный день:</b> ${d.settlement_day} число</p><p><b>Доход:</b> ${rub(p.income)}</p><p><b>Расход:</b> ${rub(p.expenses)}</p><p><b>Доп. вложения:</b> ${rub(p.investments)}</p><p><b>Прибыль:</b> ${rub(p.profit)}</p><p><b>Инвестору:</b> ${rub(p.investor_amount)} ${p.investor_percent?'('+p.investor_percent+'%)':''}</p><p><b>Собственнику:</b> ${rub(p.owner_amount)}</p><p><b>Простой:</b> ${p.downtime_days||0} дн.</p><button onclick="closePeriod('${code}')">Закрыть расчетный период</button></div><div class="card"><h3>История закрытых периодов</h3><table><tr><th>Период</th><th>Доход</th><th>Расход</th><th>Прибыль</th><th>Инвестору</th><th>Собственнику</th><th>Простой</th><th>Закрыт</th></tr>${d.closed_periods.map(x=>`<tr><td>${x.start_date} — ${x.end_date}</td><td>${rub(x.income)}</td><td>${rub(x.expenses)}</td><td>${rub(x.profit)}</td><td>${rub(x.investor_amount)}</td><td>${rub(x.owner_amount)}</td><td>${x.downtime_days||0} дн.</td><td>${x.closed_at}</td></tr>`).join('')}</table></div>`; document.getElementById('carCard').innerHTML=html; window.scrollTo(0,document.getElementById('carCard').offsetTop)}
async function closePeriod(code){if(!confirm('Закрыть расчетный период по машине '+code+'?'))return;let r=await api('/api/close-period/'+code,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});alert(r.message);await load();await openPeriod(code)}
async function openCar(code){let d=await api('/api/car/'+code); if(!d.ok){alert(d.message);return} let c=d.car; let html=`<div class="card"><h2>${c.code} ${c.brand||''} ${c.model||''}</h2><p><b>Госномер:</b> ${c.plate||''}</p><p><b>Год:</b> ${c.year||''}</p><p><b>Пробег:</b> ${c.mileage||0}</p><p><b>Стоимость покупки:</b> ${rub(c.purchase_price)}</p><p><b>Доп. вложения:</b> ${rub(c.investments)}</p><p><b>Полная стоимость:</b> ${rub(c.full_cost)}</p><p><b>Доход:</b> ${rub(c.income)}</p><p><b>Расход:</b> ${rub(c.expenses)}</p><p><b>Прибыль:</b> ${rub(c.profit)}</p><p><b>Дни простоя:</b> ${c.downtime_days||0} дн.</p><p><b>Инвестор:</b> ${c.investor_name||'-'} ${c.investor_percent?'('+c.investor_percent+'%)':''}</p><p><button onclick="openPeriod('${c.code}')">Открыть расчетный период</button></p></div><div class="card"><h3>Календарь изменений</h3>${renderCalendar(d.operations)}</div><div class="card"><h3>История машины таблицей</h3><table><tr><th>Дата</th><th>Тип</th><th>Описание</th><th>Сумма</th><th>Пробег</th><th>Сообщение</th></tr>${d.operations.map(o=>`<tr><td>${o.date}</td><td>${o.type}</td><td>${o.description||''}</td><td>${rub(o.amount)}</td><td>${o.mileage||''}</td><td>${o.raw||''}</td></tr>`).join('')}</table></div>`; document.getElementById('carCard').innerHTML=html; window.scrollTo(0,document.getElementById('carCard').offsetTop)}
async function loadOps(){let o=await api('/api/operations'); ops.innerHTML='<tr><th>Дата</th><th>Машина</th><th>Тип</th><th>Описание</th><th>Сумма</th><th>Сообщение</th></tr>'+o.map(x=>`<tr><td>${x.date}</td><td>${x.car_code}</td><td>${x.type}</td><td>${x.description||''}</td><td>${rub(x.amount)}</td><td>${x.raw||''}</td></tr>`).join('')}
async function load(){await loadSummary(); await loadInvestors(); await loadCars(currentFilter); await loadOps()}
async function add(){let m=msg.value;try{let r=await api('/api/add',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:m})});res.innerText=r.message||JSON.stringify(r);if(r.ok){msg.value=''}await load()}catch(e){res.innerText='Ошибка записи: '+e}}
async function addCar(){let payload={owner_type:owner_type.value,code:code.value,brand:brand.value,model:model.value,plate:plate.value,year:year.value,purchase_date:purchase_date.value,purchase_price:purchase_price.value,mileage:mileage.value,investor_name:investor_name.value,investor_percent:investor_percent.value,settlement_day:settlement_day.value}; let r=await api('/api/add-car',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); carRes.innerText=r.message; load()}
msg.addEventListener('keydown',e=>{if(e.key==='Enter')add()}); load();
</script></body></html>
"""
